spring:
  datasource:
    url: jdbc:mysql://180.76.175.230:3306/celling_price?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true
    username: root
    password: admin2587
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://122.51.90.142:3306/celling_price?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true
#    username: root
#    password: qwe@#$$OO.
#    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 2587

    spring:
      datasource:
        url: jdbc:mysql://127.0.0.1:3306/celling_price?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true
        username: root
        password: admin2587
        driver-class-name: com.mysql.cj.jdbc.Driver
      redis:
        host: localhost
        port: 6379
        password: 2587